### PR TITLE
change build system, use GNU autotools

### PR DESCRIPTION
**Pull request by andy5995**
I did this in separate commits so you can get a clearer idea of the steps.

I started with configure.ac, Makefile.am, and src/Makefile.am (https://github.com/lib-x/xstr/commit/2a8bb919e5310fdf52c081060eb8e7da22ba26ab)

Once those 3 files were created and edited, I ran `autoreconf -ivf` to generate the files that I added in https://github.com/lib-x/xstr/commit/34148ccb20762a2b21d906e5eef0da013d38e5e9 (Actually not all the files are generated, but copied from the GNU autotools installation).

Note I updated the build instructions in the README. The "build" dir isn't required but it keeps things a little bit cleaner for those building the program (and for maintainers, too)

One way for you to test this is: when you run configure, use the prefix option:

    xstr/build$ `../configure --prefix=$PWD/temp_usr`

Then after you run `make install`, the files will be installed to xstr/build/temp_usr

You can use `make uninstall` to uninstall.

You can create a distribution archive with `make dist`, but first you'd want to use `make distcheck` to ensure all required files will be included.

### CODE REVIEW

**Comment by andy5995** [comment]
Oh, I forgot to make a rule for building example.c. I'll work on that now.

**Comment by the-sushi** [comment]
Can some of the files be moved to a build directory? It seems really cluttered with all the files in the root directory

**Comment by andy5995** [comment]
> Can some of the files be moved to a build directory? It seems really cluttered with all the files in the root directory

Done. I used the name "build-aux" because that's commonly used. https://www.gnu.org/software/autoconf/manual/autoconf-2.65/html_node/Input.html

**Comment by the-sushi** [comment]
Thanks.

**Comment by andy5995** [comment]
You're welcome.

The only files you should ever need to edit is configure.ac and Makefile.am. Then to apply the changes, use `autoreconf -iv`. Sometimes add an -f.

**Pull request merged**
